GET http://localhost:5000/api/grade

###
POST http://localhost:5000/api/grade
Content-Type: application/json

{
    "grade": 0,
    "wilder": "Michael Scott",
    "skill": "HTML"
}

###
DELETE http://localhost:5000/api/grade

{
    "wilderId": 2, 
}